---
# handlers file for setup-apache

- name: start httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: start apache2
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"     


