---
# tasks file for setup-apache

- name: install httpd
  yum:
    name: httpd
    state: latest
  when: ansible_os_family == "RedHat"

- name: install apache2
  apt:
    name: apache2
    state: latest
  when: ansible_os_family == "Debian"   

- name: copy index.html
  template:
    src: ../templates/index.html
    dest: "{{ dir }}"
    mode: 0666

- name: start httpd 
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"
  notify:
    - start httpd

- name: start apache2
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"
  notify:
    - start apache2




